### ISSUE TITLE
Please use em units instead of px's. Only use px's when it needs to be super specific.

### ISSUE THREAD

**Issue by JustinLung** [Fabienne02/css-to-the-rescue-2122#4]
https://github.com/Fabienne02/Control-panel/blob/21c6979f9448e167fd2a1cd250fec74762be1f7c/docs/style/styles.css#L25-L26

**Comment by Fabienne02** [comment]
400px is 25.000em, is px dan niet overzichtelijker?

**Comment by JustinLung** [comment]
400/16= 25em dat kan gewoon :)
