### ISSUE TITLE
Please be consistent of using your units as above this code, you are using pixels and here your are using %

### ISSUE THREAD

**Issue by JustinLung** [Fabienne02/css-to-the-rescue-2122#5]
https://github.com/Fabienne02/Control-panel/blob/a0d5b9f892f4bb19d45e50a5ebf25d042be53941/docs/style/styles.css#L407-L408

**Comment by Fabienne02** [comment]
is het wel okay px te gebruiken voor height - witdh, em voor specafieke kleine getallen en % voor margins etc?
